config/routes.rb
Rails.application.routes.draw do
  root to: "jobs#premium"

  resources :companies, only: [:new, :create]
  
  resources :jobs do
    post "comments", to: "comments#create"
  end
  delete 'comments/:id', to: 'comments#destroy', as: :comment
  get 'hello/world'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :job
	validates_presence_of :name, :body
end

app/models/company.rb
require "bcrypt"

class Company < ActiveRecord::Base
	# attr_accssible :email, :name, :password
	#validate_presence_of :email, :name, :password
	validates_presence_of :name, :email, :password, :password_confirmation
	validates_uniqueness_of :email
	validates_length_of :password, minimum: 6
	validates_confirmation_of :password

	def password=(new_password)
		@password = new_password
		self.encrypted_password = BCrypt::Password.create(@password)		
	end

	def password
		@password		
	end
end

app/models/job.rb
class Job < ActiveRecord::Base
	has_many :comments
	validates_presence_of :description, :title
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	
	# def new
 #    	@comment = Comment.new
 #  	end


	def create
	    @job = Job.find(params[:job_id])
	    @comment = @job.comments.build(comment_params)

	    if sucess = @comment.save
	    end

	    respond_to do |format|
	    	format.html do
		      if sucess
		        flash[:notice] = 'Job was successfully created.' 
		        
		      else
		        
		        flash[:alert] = "Por favor preencha todos os campos"
		        
		      end
	      	  redirect_to @job
	    	end
	    	format.js
	    end
  	end

  	def destroy  		
  		@comment = Comment.find(params[:id])
  		@comment.destroy
  		redirect_to @comment.job, notice: "Comentario excluido com sucesso!"  		
  	end
	
	private
	def comment_params
      params.require(:comment).permit(:name, :body)
    end

end	

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  
	
	def new
		@company = Company.new
	end
	
	def create
    @company = Company.new(company_params)

    respond_to do |format|
      if @company.save
        format.html { redirect_to root_path, notice: 'company was successfully created.' }
        
      else
        format.html { render :new }
        
      end
    end
  end
	
	private
    def company_params
      params.require(:company).permit(:name, :email, :password, :password_confirmation)
    end

	
end

app/controllers/hello_controller.rb
class HelloController < ApplicationController
  def world
  end
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_action :set_job, only: [:show, :edit, :update, :destroy]

  # GET /jobs
  # GET /jobs.json
  def index
    @jobs = Job.all
  end

  # def premium
  #   @jobs = Job.where(premium: true).all
  # end

 	def premium
    	@jobs = Job.where(premium: true).all.
      paginate(page: params[:page], per_page: 5)
  	end
  # GET /jobs/1
  # GET /jobs/1.json
  def show
  end

  # GET /jobs/new
  def new
    @job = Job.new
  end

  # GET /jobs/1/edit
  def edit
  end

  # POST /jobs
  # POST /jobs.json
  def create
    @job = Job.new(job_params)

    respond_to do |format|
      if @job.save
        format.html { redirect_to @job, notice: 'Job was successfully created.' }
        format.json { render :show, status: :created, location: @job }
      else
        format.html { render :new }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /jobs/1
  # PATCH/PUT /jobs/1.json
  def update
    respond_to do |format|
      if @job.update(job_params)
        format.html { redirect_to @job, notice: 'Job was successfully updated.' }
        format.json { render :show, status: :ok, location: @job }
      else
        format.html { render :edit }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /jobs/1
  # DELETE /jobs/1.json
  def destroy
    @job.destroy
    respond_to do |format|
      format.html { redirect_to jobs_url, notice: 'Job was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_job
      @job = Job.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def job_params
      params.require(:job).permit(:title, :description, :premium)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/hello_helper.rb
module HelloHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
	def job_title(job)
		title = h(job.title)

		if job.premium
			title + content_tag(:string, " (premium)")
		else
			title
		end			
	end		
end

app/views/comments/_comment.html.erb
<h4><%= comment.name %> said:</h4>
<%= simple_format comment.body %>
Sent <%= time_ago_in_words comment.created_at %> ago
<%= link_to "Destroy", comment_path(comment), method: :delete, confirm: "Are you sure?" %>

app/views/comments/_form.html.erb
<%= form_for [@job, Comment.new], html: { class: 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :name, class: 'control-label' %>
    <div class="controls">
      <%= f.text_field :name %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :body, class: 'control-label' %>
    <div class="controls">
      <%= f.text_area :body, rows: 5 %>
    </div>
  </div>
  <div class="control-group controls">
    <%= f.submit "Send", class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/companies/_form.html.erb
<%= form_for(@company, html: { class: 'form-horizontal' }) do |f| %>
  <% if @company.errors.any? %>
    <div class="alert alert-error">
      <h3><%= pluralize(@company.errors.count, "error") %> prohibited this company from being saved:</h3>

      <ul>
      <% @company.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="control-group">
    <%= f.label :name, class: 'control-label' %>
    <div class="controls">
      <%= f.text_field :name %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :email, class: 'control-label' %>
    <div class="controls">
      <%= f.text_field :email %>
    </div>
  </div>
 <div class="control-group">
    <%= f.label :password, class: 'control-label' %>
    <div class="controls">
      <%= f.password_field :password %>
    </div>
  </div>
   <div class="control-group">
    <%= f.label :password_confirmation, class: 'control-label' %>
    <div class="controls">
      <%= f.password_field :password_confirmation %>
    </div>
  </div>

  <div class="control-group controls">
    <%= f.submit class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/companies/new.html.erb
<% if notice %><p class="alert alert-success"><%= notice %></p><% end %>
<% if alert %><p class="alert alert-error"><%= alert %></p><% end %>

<h1>New Company</h1>

<%= render "form" %>

<%= link_to "Back", root_path %>

app/views/hello/world.html.erb
<h1>Hello World</h1>
<strong><%= Time.now %></strong>

app/views/jobs/11_form.html.erb
<%= form_for(@job) do |f| %>
  <% if @job.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@job.errors.count, "error") %> prohibited this job from being saved:</h2>

      <ul>
      <% @job.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
    <div class="field">
    <%= f.label :premium %><br>
    <%= f.check_box :premium %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/jobs/_form.html.erb
<%= form_for(@job, html: { class: 'form-horizontal' }) do |f| %>
  <% if @job.errors.any? %>
    <div class="alert alert-error">
      <h3><%= pluralize(@job.errors.count, "error") %> prohibited this job from being saved:</h3>

      <ul>
      <% @job.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="control-group">
    <%= f.label :title, class: 'control-label' %>
    <div class="controls">
      <%= f.text_field :title %>
    </div>
  </div>
  <div class="control-group">
    <div class="controls">
      <%= f.label :premium, class: 'checkbox' do %>
        <%= f.check_box :premium, rows: 10 %> Premium
      <% end %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :description, class: 'control-label' %>
    <div class="controls">
      <%= f.text_area :description, rows: 10 %>
    </div>
  </div>
  <div class="control-group controls">
    <%= f.submit class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/jobs/_job.html.erb
<h3>
  <%= job.title %>
  <% if job.premium %>
    <strong>(premium)</strong>
  <% end %>
</h3>

<%= simple_format job.description %>

<p>
  <%= pluralize(job.comments.size, "comment") %> |
  <%= link_to 'Show', job %> |
  <%= link_to 'Edit', edit_job_path(job) %> |
  <%= link_to 'Destroy', job, method: :delete, data: { confirm: 'Are you sure?' } %>
</p>

app/views/jobs/edit.html.erb
<h1>Editing job</h1>

<%= render 'form' %>

<%= link_to 'Show', @job %> |
<%= link_to 'Back', jobs_path %>

app/views/jobs/index.html.erb
<%= render @jobs %>

app/views/jobs/new.html.erb
<h1>New job</h1>

<%= render 'form' %>

<%= link_to 'Back', jobs_path %>

app/views/jobs/premium.html.erb
<h1>Premium jobs</h1>

<%= render @jobs %>
<%= will_paginate @jobs %>

app/views/jobs/show.html.erb
<% if notice %><p class="alert alert-success"><%= notice %></p><% end %>
<% if alert %><p class="alert alert-error"><%= alert %></p><% end %>

<h1><%= job_title @job %></h1>

<%= simple_format @job.description %>

<p>
  <%= pluralize(@job.comments.size, "comment") %> |
  <%= link_to 'Edit', edit_job_path(@job) %> |
  <%= link_to 'Back', jobs_path %>
</p>

<h2>Send a new comment</h2>
<%= render "comments/form" %>

<h2>Comments</h2>
<%= render @job.comments %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8" />
  <title>JobBoard</title>
  <%= stylesheet_link_tag "application", :media => "all" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="navbar navbar-fixed-top">
    <div class="navbar-inner">
      <div class="container">
        <a class="brand" href="/" title="Job Board">Job Board</a>

        <ul id="app-menu" class="nav pull-right">
          <li><%= link_to "Premium Jobs", root_path %></li>
          <li><%= link_to "All Jobs", jobs_path %></li>
          <li><%= link_to "New Job", new_job_path %></li>
          <li><%= link_to "Hello World", hello_world_path %></li>
        </ul>
      </div>
    </div>
  </div>

  <div class="container">
    <%= yield %>
  </div>

  <%= javascript_include_tag "application" %>
</body>
</html>